name = "sveltekit-accelerator"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"

# Environment variables (these will be overridden by dashboard settings)
[vars]
PUBLIC_APP_NAME = "SvelteKit Accelerator"
PUBLIC_APP_URL = "https://sveltekit-accelerator.pages.dev"

# Pages configuration
[[d1_databases]]
binding = "DB" # Available in your app as env.DB
database_name = "sveltekit-accelerator-db"
database_id = "your-database-id" # Replace with actual D1 database ID

# R2 storage bucket for file uploads (optional)
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "sveltekit-accelerator-storage"

# KV namespace for caching (optional)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id" # Replace with actual KV namespace ID

# Durable Objects (optional, for real-time features)
# [[durable_objects.bindings]]
# name = "WEBSOCKET"
# class_name = "WebSocketDurableObject"
# script_name = "sveltekit-accelerator"

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   { pattern = "yourdomain.com", custom_domain = true },
#   { pattern = "www.yourdomain.com", custom_domain = true }
# ]

# Development settings
[dev]
port = 5173
local_protocol = "http"

# Preview deployments
[env.preview]
vars = { PUBLIC_APP_URL = "https://preview.sveltekit-accelerator.pages.dev" }

# Production deployments
[env.production]
vars = { PUBLIC_APP_URL = "https://sveltekit-accelerator.pages.dev" } 