name = "sk-accelerator"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Node.js compatibility for server-side modules
compatibility_flags = ["nodejs_compat"]

# Note: Environment variables should be set in Cloudflare Pages dashboard
# Don't define PUBLIC_APP_URL here as it conflicts with Pages environment variables

# Note: This project uses Supabase for database and storage
# All database operations go through Supabase, not Cloudflare D1
# File storage uses Supabase Storage, not R2

# R2 storage bucket for file uploads (optional - currently using Supabase Storage)
# Uncomment if you want to use R2 in addition to or instead of Supabase Storage
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "sveltekit-accelerator-storage"

# Durable Objects (optional, for real-time features)
# [[durable_objects.bindings]]
# name = "WEBSOCKET"
# class_name = "WebSocketDurableObject"
# script_name = "sveltekit-accelerator"

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   { pattern = "yourdomain.com", custom_domain = true },
#   { pattern = "www.yourdomain.com", custom_domain = true }
# ] 