name = "sk-accelerator"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Node.js compatibility for server-side modules
compatibility_flags = ["nodejs_compat"]

# Environment variables (these will be overridden by dashboard settings)
[vars]
PUBLIC_APP_NAME = "SvelteKit Accelerator"
PUBLIC_APP_URL = "https://sveltekit-accelerator.pages.dev"

# Note: This project uses Supabase for database and storage
# All database operations go through Supabase, not Cloudflare D1
# File storage uses Supabase Storage, not R2

# R2 storage bucket for file uploads (optional - currently using Supabase Storage)
# Uncomment if you want to use R2 in addition to or instead of Supabase Storage
# [[r2_buckets]]
# binding = "STORAGE"
# bucket_name = "sveltekit-accelerator-storage"

# Durable Objects (optional, for real-time features)
# [[durable_objects.bindings]]
# name = "WEBSOCKET"
# class_name = "WebSocketDurableObject"
# script_name = "sveltekit-accelerator"

# Custom domains (configure in Cloudflare dashboard)
# routes = [
#   { pattern = "yourdomain.com", custom_domain = true },
#   { pattern = "www.yourdomain.com", custom_domain = true }
# ]

# Development settings
[dev]
port = 5173
local_protocol = "http"

# Preview deployments
[env.preview]
vars = { PUBLIC_APP_URL = "https://preview.sveltekit-accelerator.pages.dev" }

# Production deployments
[env.production]
vars = { PUBLIC_APP_URL = "https://sveltekit-accelerator.pages.dev" } 